return {
 ["htmlfiles"]={ "export-004-div.html" },
 ["htmlroot"]="export-004-div.html",
 ["identifier"]="8df5a3bb-4180-ab07-93e0-4c53d6d2852c",
 ["imagefile"]="styles/export-004-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-004",
 ["stylepath"]="styles",
 ["styles"]={ "export-004-defaults.css", "export-004-images.css", "export-004-styles.css" },
 ["xhtmlfiles"]={ "export-004-tag.xhtml" },
 ["xmlfiles"]={ "export-004-raw.xml" },
}