return {
 ["htmlfiles"]={ "export-004-div.html" },
 ["htmlroot"]="export-004-div.html",
 ["identifier"]="4fec3646-44f5-bc02-e12d-a5a98dc07618",
 ["imagefile"]="styles/export-004-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-004",
 ["stylepath"]="styles",
 ["styles"]={ "export-004-defaults.css", "export-004-images.css", "export-004-styles.css" },
 ["title"]="export-004",
 ["xhtmlfiles"]={ "export-004-tag.xhtml" },
 ["xmlfiles"]={ "export-004-raw.xml" },
}