return {
 ["htmlfiles"]={ "export-004-div.html" },
 ["htmlroot"]="export-004-div.html",
 ["identifier"]="5950c16c-478e-893b-2382-c14c2e360afc",
 ["imagefile"]="styles/export-004-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-004",
 ["stylepath"]="styles",
 ["styles"]={ "export-004-defaults.css", "export-004-images.css", "export-004-styles.css" },
 ["xhtmlfiles"]={ "export-004-tag.xhtml" },
 ["xmlfiles"]={ "export-004-raw.xml" },
}