return {
 ["htmlfiles"]={ "tables-001-div.html" },
 ["htmlroot"]="tables-001-div.html",
 ["identifier"]="6a32bde0-499a-bb76-38ea-f0f8a96a004d",
 ["imagefile"]="styles/tables-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tables-001",
 ["stylepath"]="styles",
 ["styles"]={ "tables-001-defaults.css", "tables-001-images.css", "tables-001-styles.css" },
 ["xhtmlfiles"]={ "tables-001-tag.xhtml" },
 ["xmlfiles"]={ "tables-001-raw.xml" },
}