return {
 ["htmlfiles"]={ "export-006-div.html" },
 ["htmlroot"]="export-006-div.html",
 ["identifier"]="e5074cfb-4a77-907d-cef9-3dd63b077104",
 ["imagefile"]="styles/export-006-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-006",
 ["stylepath"]="styles",
 ["styles"]={ "export-006-defaults.css", "export-006-images.css", "export-006-styles.css" },
 ["xhtmlfiles"]={ "export-006-tag.xhtml" },
 ["xmlfiles"]={ "export-006-raw.xml" },
}