return {
 ["htmlfiles"]={ "tagged-008-div.html" },
 ["htmlroot"]="tagged-008-div.html",
 ["identifier"]="afda0292-4864-b051-3c6c-4adad72c8041",
 ["imagefile"]="styles/tagged-008-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-008",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-008-defaults.css", "tagged-008-images.css", "tagged-008-styles.css" },
 ["title"]="tagged-008",
 ["xhtmlfiles"]={ "tagged-008-tag.xhtml" },
 ["xmlfiles"]={ "tagged-008-raw.xml" },
}