return {
 ["htmlfiles"]={ "spaces-002-div.html" },
 ["htmlroot"]="spaces-002-div.html",
 ["identifier"]="325f6f3b-413c-bf37-d51e-cdd33c6dd557",
 ["imagefile"]="styles/spaces-002-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="spaces-002",
 ["stylepath"]="styles",
 ["styles"]={ "spaces-002-defaults.css", "spaces-002-images.css", "spaces-002-styles.css" },
 ["title"]="spaces-002",
 ["xhtmlfiles"]={ "spaces-002-tag.xhtml" },
 ["xmlfiles"]={ "spaces-002-raw.xml" },
}