return {
 ["htmlfiles"]={ "spaces-002-div.html" },
 ["htmlroot"]="spaces-002-div.html",
 ["identifier"]="f2f83fcc-4c4f-81bb-fbee-7482b76c7e18",
 ["imagefile"]="styles/spaces-002-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="spaces-002",
 ["stylepath"]="styles",
 ["styles"]={ "spaces-002-defaults.css", "spaces-002-images.css", "spaces-002-styles.css" },
 ["xhtmlfiles"]={ "spaces-002-tag.xhtml" },
 ["xmlfiles"]={ "spaces-002-raw.xml" },
}