return {
 ["htmlfiles"]={ "spaces-002-div.html" },
 ["htmlroot"]="spaces-002-div.html",
 ["identifier"]="ca990b70-4a28-b6cb-c6f8-554348d87636",
 ["imagefile"]="styles/spaces-002-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="spaces-002",
 ["stylepath"]="styles",
 ["styles"]={ "spaces-002-defaults.css", "spaces-002-images.css", "spaces-002-styles.css" },
 ["xhtmlfiles"]={ "spaces-002-tag.xhtml" },
 ["xmlfiles"]={ "spaces-002-raw.xml" },
}