return {
 ["htmlfiles"]={ "export-008-div.html" },
 ["htmlroot"]="export-008-div.html",
 ["identifier"]="c8b4ce2c-44af-9625-a412-5d9ed5d29a98",
 ["imagefile"]="styles/export-008-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-008",
 ["stylepath"]="styles",
 ["styles"]={ "export-008-defaults.css", "export-008-images.css", "export-008-styles.css" },
 ["xhtmlfiles"]={ "export-008-tag.xhtml" },
 ["xmlfiles"]={ "export-008-raw.xml" },
}