return {
 ["htmlfiles"]={ "export-008-div.html" },
 ["htmlroot"]="export-008-div.html",
 ["identifier"]="db84f9e2-4063-884a-e46b-cefcf02e50be",
 ["imagefile"]="styles/export-008-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-008",
 ["stylepath"]="styles",
 ["styles"]={ "export-008-defaults.css", "export-008-images.css", "export-008-styles.css" },
 ["xhtmlfiles"]={ "export-008-tag.xhtml" },
 ["xmlfiles"]={ "export-008-raw.xml" },
}