return {
 ["htmlfiles"]={ "ignored-001-div.html" },
 ["htmlroot"]="ignored-001-div.html",
 ["identifier"]="f0ff7066-4a2e-8b71-650f-2b0da6ee787b",
 ["imagefile"]="styles/ignored-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="ignored-001",
 ["stylepath"]="styles",
 ["styles"]={ "ignored-001-defaults.css", "ignored-001-images.css", "ignored-001-styles.css" },
 ["xhtmlfiles"]={ "ignored-001-tag.xhtml" },
 ["xmlfiles"]={ "ignored-001-raw.xml" },
}