return {
 ["htmlfiles"]={ "ignored-001-div.html" },
 ["htmlroot"]="ignored-001-div.html",
 ["identifier"]="5199bd1b-4633-b76b-b84b-f09b76f6bc4f",
 ["imagefile"]="styles/ignored-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="ignored-001",
 ["stylepath"]="styles",
 ["styles"]={ "ignored-001-defaults.css", "ignored-001-images.css", "ignored-001-styles.css" },
 ["title"]="ignored-001",
 ["xhtmlfiles"]={ "ignored-001-tag.xhtml" },
 ["xmlfiles"]={ "ignored-001-raw.xml" },
}