return {
 ["htmlfiles"]={ "hz-001-div.html" },
 ["htmlroot"]="hz-001-div.html",
 ["identifier"]="8ee20310-4b17-8c06-ca9a-5b64edeaed82",
 ["imagefile"]="styles/hz-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="hz-001",
 ["stylepath"]="styles",
 ["styles"]={ "hz-001-defaults.css", "hz-001-images.css", "hz-001-styles.css" },
 ["xhtmlfiles"]={ "hz-001-tag.xhtml" },
 ["xmlfiles"]={ "hz-001-raw.xml" },
}