return {
 ["htmlfiles"]={ "hz-001-div.html" },
 ["htmlroot"]="hz-001-div.html",
 ["identifier"]="c7ba16e9-4a79-a12f-234f-d3b1c859bd35",
 ["imagefile"]="styles/hz-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="hz-001",
 ["stylepath"]="styles",
 ["styles"]={ "hz-001-defaults.css", "hz-001-images.css", "hz-001-styles.css" },
 ["xhtmlfiles"]={ "hz-001-tag.xhtml" },
 ["xmlfiles"]={ "hz-001-raw.xml" },
}