return {
 ["htmlfiles"]={ "tagged-010-div.html" },
 ["htmlroot"]="tagged-010-div.html",
 ["identifier"]="ab012c98-4089-b55f-b1f2-457a0b01be7a",
 ["imagefile"]="styles/tagged-010-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-010",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-010-defaults.css", "tagged-010-images.css", "tagged-010-styles.css" },
 ["title"]="tagged-010",
 ["xhtmlfiles"]={ "tagged-010-tag.xhtml" },
 ["xmlfiles"]={ "tagged-010-raw.xml" },
}