return {
 ["htmlfiles"]={ "tagged-010-div.html" },
 ["htmlroot"]="tagged-010-div.html",
 ["identifier"]="4e793dba-41f9-b0c3-06ab-f68f5cb42210",
 ["imagefile"]="styles/tagged-010-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-010",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-010-defaults.css", "tagged-010-images.css", "tagged-010-styles.css" },
 ["xhtmlfiles"]={ "tagged-010-tag.xhtml" },
 ["xmlfiles"]={ "tagged-010-raw.xml" },
}