return {
 ["htmlfiles"]={ "export-007-div.html" },
 ["htmlroot"]="export-007-div.html",
 ["identifier"]="e543af6a-49ac-9f1a-0547-c2891d66dfd2",
 ["imagefile"]="styles/export-007-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-007",
 ["stylepath"]="styles",
 ["styles"]={ "export-007-defaults.css", "export-007-images.css", "export-007-styles.css" },
 ["title"]="export-007",
 ["xhtmlfiles"]={ "export-007-tag.xhtml" },
 ["xmlfiles"]={ "export-007-raw.xml" },
}