return {
 ["htmlfiles"]={ "symbolsets-001-div.html" },
 ["htmlroot"]="symbolsets-001-div.html",
 ["identifier"]="1c588bc9-40df-b577-8805-9beab710f871",
 ["imagefile"]="styles/symbolsets-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="symbolsets-001",
 ["stylepath"]="styles",
 ["styles"]={ "symbolsets-001-defaults.css", "symbolsets-001-images.css", "symbolsets-001-styles.css" },
 ["title"]="symbolsets-001",
 ["xhtmlfiles"]={ "symbolsets-001-tag.xhtml" },
 ["xmlfiles"]={ "symbolsets-001-raw.xml" },
}