return {
 ["htmlfiles"]={ "symbolsets-001-div.html" },
 ["htmlroot"]="symbolsets-001-div.html",
 ["identifier"]="cbcb3bec-4577-afd3-700f-66c5a13ecbbe",
 ["imagefile"]="styles/symbolsets-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="symbolsets-001",
 ["stylepath"]="styles",
 ["styles"]={ "symbolsets-001-defaults.css", "symbolsets-001-images.css", "symbolsets-001-styles.css" },
 ["xhtmlfiles"]={ "symbolsets-001-tag.xhtml" },
 ["xmlfiles"]={ "symbolsets-001-raw.xml" },
}