return {
 ["htmlfiles"]={ "itemize-001-div.html" },
 ["htmlroot"]="itemize-001-div.html",
 ["identifier"]="0a368e2c-4dbc-a1cd-91fc-185e02faba44",
 ["imagefile"]="styles/itemize-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="itemize-001",
 ["stylepath"]="styles",
 ["styles"]={ "itemize-001-defaults.css", "itemize-001-images.css", "itemize-001-styles.css" },
 ["xhtmlfiles"]={ "itemize-001-tag.xhtml" },
 ["xmlfiles"]={ "itemize-001-raw.xml" },
}