return {
 ["htmlfiles"]={ "tagged-003-div.html" },
 ["htmlroot"]="tagged-003-div.html",
 ["identifier"]="3cdecaef-4f55-8909-de63-558af6d9afc3",
 ["imagefile"]="styles/tagged-003-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-003",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-003-defaults.css", "tagged-003-images.css", "tagged-003-styles.css" },
 ["title"]="tagged-003",
 ["xhtmlfiles"]={ "tagged-003-tag.xhtml" },
 ["xmlfiles"]={ "tagged-003-raw.xml" },
}