return {
 ["htmlfiles"]={ "export-001-div.html" },
 ["htmlroot"]="export-001-div.html",
 ["identifier"]="e019a9c5-4f97-b6c8-ba87-1c28eb3575bc",
 ["imagefile"]="styles/export-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-001",
 ["stylepath"]="styles",
 ["styles"]={ "export-001-defaults.css", "export-001-images.css", "export-001-styles.css" },
 ["xhtmlfiles"]={ "export-001-tag.xhtml" },
 ["xmlfiles"]={ "export-001-raw.xml" },
}