return {
 ["htmlfiles"]={ "export-001-div.html" },
 ["htmlroot"]="export-001-div.html",
 ["identifier"]="f279b445-416b-88b3-d4c1-26668be5f32e",
 ["imagefile"]="styles/export-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-001",
 ["stylepath"]="styles",
 ["styles"]={ "export-001-defaults.css", "export-001-images.css", "export-001-styles.css" },
 ["xhtmlfiles"]={ "export-001-tag.xhtml" },
 ["xmlfiles"]={ "export-001-raw.xml" },
}