return {
 ["htmlfiles"]={ "export-001-div.html" },
 ["htmlroot"]="export-001-div.html",
 ["identifier"]="e0868a9d-4e4e-a4bc-3042-a92edeb277f8",
 ["imagefile"]="styles/export-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-001",
 ["stylepath"]="styles",
 ["styles"]={ "export-001-defaults.css", "export-001-images.css", "export-001-styles.css" },
 ["xhtmlfiles"]={ "export-001-tag.xhtml" },
 ["xmlfiles"]={ "export-001-raw.xml" },
}