return {
 ["htmlfiles"]={ "spaces-001-div.html" },
 ["htmlroot"]="spaces-001-div.html",
 ["identifier"]="3b345482-4dc3-b0d7-c612-97bc29e8eeba",
 ["imagefile"]="styles/spaces-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="spaces-001",
 ["stylepath"]="styles",
 ["styles"]={ "spaces-001-defaults.css", "spaces-001-images.css", "spaces-001-styles.css" },
 ["xhtmlfiles"]={ "spaces-001-tag.xhtml" },
 ["xmlfiles"]={ "spaces-001-raw.xml" },
}