return {
 ["htmlfiles"]={ "spaces-001-div.html" },
 ["htmlroot"]="spaces-001-div.html",
 ["identifier"]="9db41511-4a6d-9e3a-2e5f-bd28b0ef74af",
 ["imagefile"]="styles/spaces-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="spaces-001",
 ["stylepath"]="styles",
 ["styles"]={ "spaces-001-defaults.css", "spaces-001-images.css", "spaces-001-styles.css" },
 ["xhtmlfiles"]={ "spaces-001-tag.xhtml" },
 ["xmlfiles"]={ "spaces-001-raw.xml" },
}