return {
 ["htmlfiles"]={ "spaces-001-div.html" },
 ["htmlroot"]="spaces-001-div.html",
 ["identifier"]="2791fc58-4a5a-a6ab-bfeb-133b5437cb61",
 ["imagefile"]="styles/spaces-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="spaces-001",
 ["stylepath"]="styles",
 ["styles"]={ "spaces-001-defaults.css", "spaces-001-images.css", "spaces-001-styles.css" },
 ["title"]="spaces-001",
 ["xhtmlfiles"]={ "spaces-001-tag.xhtml" },
 ["xmlfiles"]={ "spaces-001-raw.xml" },
}