return {
 ["htmlfiles"]={ "math-002-div.html" },
 ["htmlroot"]="math-002-div.html",
 ["identifier"]="53eadd56-4407-b19f-e9d4-29d86e8ed67e",
 ["imagefile"]="styles/math-002-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="math-002",
 ["stylepath"]="styles",
 ["styles"]={ "math-002-defaults.css", "math-002-images.css", "math-002-styles.css" },
 ["xhtmlfiles"]={ "math-002-tag.xhtml" },
 ["xmlfiles"]={ "math-002-raw.xml" },
}