return {
 ["htmlfiles"]={ "simple-001-div.html" },
 ["htmlroot"]="simple-001-div.html",
 ["identifier"]="f91a8bf7-47bb-a1c1-ad44-b29c45bfb2fc",
 ["imagefile"]="styles/simple-001-images.css",
 ["imagepath"]="images",
 ["images"]={
  ["image>1"]={
   ["element"]="image",
   ["height"]="3.052cm",
   ["id"]="image-1",
   ["name"]="cow.pdf",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/cow.svg",
   ["used"]="",
   ["width"]="4.070cm",
  },
 },
 ["language"]="en",
 ["metadata"]={},
 ["name"]="simple-001",
 ["stylepath"]="styles",
 ["styles"]={ "simple-001-defaults.css", "simple-001-images.css", "simple-001-styles.css" },
 ["title"]="simple-001",
 ["xhtmlfiles"]={ "simple-001-tag.xhtml" },
 ["xmlfiles"]={ "simple-001-raw.xml" },
}