return {
 ["htmlfiles"]={ "export-005-div.html" },
 ["htmlroot"]="export-005-div.html",
 ["identifier"]="33f83ff1-4e41-8eac-fff6-0e7b30fdbb9e",
 ["imagefile"]="styles/export-005-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-005",
 ["stylepath"]="styles",
 ["styles"]={ "export-005-defaults.css", "export-005-images.css", "export-005-styles.css" },
 ["xhtmlfiles"]={ "export-005-tag.xhtml" },
 ["xmlfiles"]={ "export-005-raw.xml" },
}