return {
 ["htmlfiles"]={ "tagged-005-div.html" },
 ["htmlroot"]="tagged-005-div.html",
 ["identifier"]="f5ba1f9c-42b8-a31e-e6be-5e1c65c4f5ea",
 ["imagefile"]="styles/tagged-005-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-005",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-005-defaults.css", "tagged-005-images.css", "tagged-005-styles.css" },
 ["xhtmlfiles"]={ "tagged-005-tag.xhtml" },
 ["xmlfiles"]={ "tagged-005-raw.xml" },
}