return {
 ["htmlfiles"]={ "tagged-005-div.html" },
 ["htmlroot"]="tagged-005-div.html",
 ["identifier"]="f629ca16-43a9-aa3d-e653-1c575382d109",
 ["imagefile"]="styles/tagged-005-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-005",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-005-defaults.css", "tagged-005-images.css", "tagged-005-styles.css" },
 ["xhtmlfiles"]={ "tagged-005-tag.xhtml" },
 ["xmlfiles"]={ "tagged-005-raw.xml" },
}