return {
 ["htmlfiles"]={ "tagged-005-div.html" },
 ["htmlroot"]="tagged-005-div.html",
 ["identifier"]="9671f54e-4eca-b5cd-1426-90327c10b895",
 ["imagefile"]="styles/tagged-005-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-005",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-005-defaults.css", "tagged-005-images.css", "tagged-005-styles.css" },
 ["title"]="tagged-005",
 ["xhtmlfiles"]={ "tagged-005-tag.xhtml" },
 ["xmlfiles"]={ "tagged-005-raw.xml" },
}