return {
 ["htmlfiles"]={ "export-001-div.html" },
 ["htmlroot"]="export-001-div.html",
 ["identifier"]="3ee193dc-4a8e-82ee-5105-56c8c0dcd276",
 ["imagefile"]="styles/export-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-001",
 ["stylepath"]="styles",
 ["styles"]={ "export-001-defaults.css", "export-001-images.css", "export-001-styles.css" },
 ["title"]="export-001",
 ["xhtmlfiles"]={ "export-001-tag.xhtml" },
 ["xmlfiles"]={ "export-001-raw.xml" },
}