return {
 ["htmlfiles"]={ "export-009-div.html" },
 ["htmlroot"]="export-009-div.html",
 ["identifier"]="9a854735-4737-92b1-e121-cfb272ed2bf2",
 ["imagefile"]="styles/export-009-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-009",
 ["stylepath"]="styles",
 ["styles"]={ "export-009-defaults.css", "export-009-images.css", "export-009-styles.css" },
 ["xhtmlfiles"]={ "export-009-tag.xhtml" },
 ["xmlfiles"]={ "export-009-raw.xml" },
}