return {
 ["htmlfiles"]={ "userproperties-001-div.html" },
 ["htmlroot"]="userproperties-001-div.html",
 ["identifier"]="9d7e1978-4255-9a68-1406-c1e54d20d111",
 ["imagefile"]="styles/userproperties-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="userproperties-001",
 ["stylepath"]="styles",
 ["styles"]={ "userproperties-001-defaults.css", "userproperties-001-images.css", "userproperties-001-styles.css" },
 ["xhtmlfiles"]={ "userproperties-001-tag.xhtml" },
 ["xmlfiles"]={ "userproperties-001-raw.xml" },
}