return {
 ["htmlfiles"]={ "userproperties-001-div.html" },
 ["htmlroot"]="userproperties-001-div.html",
 ["identifier"]="cbf55aa3-4d2b-9861-0692-2ae3a6b7ce18",
 ["imagefile"]="styles/userproperties-001-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="userproperties-001",
 ["stylepath"]="styles",
 ["styles"]={ "userproperties-001-defaults.css", "userproperties-001-images.css", "userproperties-001-styles.css" },
 ["title"]="userproperties-001",
 ["xhtmlfiles"]={ "userproperties-001-tag.xhtml" },
 ["xmlfiles"]={ "userproperties-001-raw.xml" },
}