return {
 ["htmlfiles"]={ "tagged-009-div.html" },
 ["htmlroot"]="tagged-009-div.html",
 ["identifier"]="63d3b84c-4325-98cf-c527-9b2c9b6d7727",
 ["imagefile"]="styles/tagged-009-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-009",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-009-defaults.css", "tagged-009-images.css", "tagged-009-styles.css" },
 ["xhtmlfiles"]={ "tagged-009-tag.xhtml" },
 ["xmlfiles"]={ "tagged-009-raw.xml" },
}