return {
 ["htmlfiles"]={ "tagged-009-div.html" },
 ["htmlroot"]="tagged-009-div.html",
 ["identifier"]="30831a23-456f-800d-6c94-5defdbe99179",
 ["imagefile"]="styles/tagged-009-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="tagged-009",
 ["stylepath"]="styles",
 ["styles"]={ "tagged-009-defaults.css", "tagged-009-images.css", "tagged-009-styles.css" },
 ["title"]="tagged-009",
 ["xhtmlfiles"]={ "tagged-009-tag.xhtml" },
 ["xmlfiles"]={ "tagged-009-raw.xml" },
}