return {
 ["htmlfiles"]={ "bold-002-div.html" },
 ["htmlroot"]="bold-002-div.html",
 ["identifier"]="47fb04bb-4ced-88a7-ace0-01015763d144",
 ["imagefile"]="styles/bold-002-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="bold-002",
 ["stylepath"]="styles",
 ["styles"]={ "bold-002-defaults.css", "bold-002-images.css", "bold-002-styles.css" },
 ["xhtmlfiles"]={ "bold-002-tag.xhtml" },
 ["xmlfiles"]={ "bold-002-raw.xml" },
}