return {
 ["htmlfiles"]={ "bold-002-div.html" },
 ["htmlroot"]="bold-002-div.html",
 ["identifier"]="867f47f1-4cb3-a302-c064-8c2e9ccf122f",
 ["imagefile"]="styles/bold-002-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="bold-002",
 ["stylepath"]="styles",
 ["styles"]={ "bold-002-defaults.css", "bold-002-images.css", "bold-002-styles.css" },
 ["title"]="bold-002",
 ["xhtmlfiles"]={ "bold-002-tag.xhtml" },
 ["xmlfiles"]={ "bold-002-raw.xml" },
}