return {
 ["htmlfiles"]={ "itemize-002-div.html" },
 ["htmlroot"]="itemize-002-div.html",
 ["identifier"]="3b5db771-48a8-8f76-83c0-7cea42e0261b",
 ["imagefile"]="styles/itemize-002-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="itemize-002",
 ["stylepath"]="styles",
 ["styles"]={ "itemize-002-defaults.css", "itemize-002-images.css", "itemize-002-styles.css" },
 ["xhtmlfiles"]={ "itemize-002-tag.xhtml" },
 ["xmlfiles"]={ "itemize-002-raw.xml" },
}