return {
 ["htmlfiles"]={ "itemize-002-div.html" },
 ["htmlroot"]="itemize-002-div.html",
 ["identifier"]="41889c43-45c2-99f0-60b9-3337cde5c11d",
 ["imagefile"]="styles/itemize-002-images.css",
 ["imagepath"]="images",
 ["images"]={},
 ["language"]="en",
 ["metadata"]={},
 ["name"]="itemize-002",
 ["stylepath"]="styles",
 ["styles"]={ "itemize-002-defaults.css", "itemize-002-images.css", "itemize-002-styles.css" },
 ["title"]="itemize-002",
 ["xhtmlfiles"]={ "itemize-002-tag.xhtml" },
 ["xmlfiles"]={ "itemize-002-raw.xml" },
}